server:
  port: 9999

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    datasource:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev
    username: root
    password: 'your_pass'
    driver-class-name: com.mysql.cj.jdbc.Driver